"""Shared document-metadata fix-up for every DOCX writer in this repo.

python-docx's default template stamps every generated file with tells that
give away the generator: author "python-docx", a description that reads
"generated by python-docx", a created/modified date frozen at
2013-12-23T23:15:00Z, and (depending on platform) an Application field in
docProps/app.xml that names a non-Word generator. None of that may ship in
a resume, cheat sheet, or cover letter.

Every DOCX writer in this repo must call apply_document_metadata(doc,
author) on the open Document before doc.save(). This is the one place the
fix lives; writers must not reimplement any part of it, so the fix cannot
drift between writers.
"""

from __future__ import annotations

import datetime as dt
import os
import re

# Matches "python-docx" or "pythondocx" case-insensitively, with or
# without the hyphen, as a final safety net over docProps/app.xml. The
# targeted field fix below (Application) already covers the one field
# python-docx actually stamps in that part; this regex is a backstop in
# case a future python-docx version adds another one.
_TELL_PATTERN = re.compile(r"python[- ]?docx", re.IGNORECASE)
_APP_PROPERTIES_PARTNAME = "/docProps/app.xml"
_NAME_FIELD_PATTERN = re.compile(r"^-\s*\*\*Name:\*\*\s*(.+?)\s*$", re.MULTILINE)


def apply_document_metadata(doc, author):
    """Overwrite python-docx's default core and extended document properties.

    Must be called on an open docx.Document before doc.save(). Sets the
    document's author and last-modified-by to the given name, stamps
    created/modified as the current time in UTC (the timezone the OOXML
    dcterms:created/modified fields require: python-docx's own writer
    always appends a "Z" suffix regardless of what datetime it is given,
    so passing anything other than a UTC-based value would silently
    mislabel a local wall-clock time as UTC), clears the default
    "generated by python-docx" description, and rewrites
    docProps/app.xml so its Application field reads "Microsoft Office
    Word" and no "python-docx" string survives anywhere in the package.

    Args:
        doc: an open docx.Document instance, not yet saved.
        author: the candidate's name, as resolved by the caller (see
            resolve_author_from_header_lines / resolve_author_from_profile
            below). This function never guesses or defaults a name.

    Raises:
        ValueError: if author is empty, blank, or not a string. There is
            no silent fallback to "python-docx" or an empty author.

    Returns:
        The same doc instance, for convenient chaining.
    """
    if not isinstance(author, str) or not author.strip():
        raise ValueError(
            "apply_document_metadata requires a non-empty author name, got %r" % (author,)
        )
    name = author.strip()
    now = dt.datetime.now(dt.timezone.utc)

    props = doc.core_properties
    props.author = name
    props.last_modified_by = name
    props.created = now
    props.modified = now
    props.comments = ""
    props.revision = 1

    _fix_extended_properties(doc)
    return doc


def _fix_extended_properties(doc):
    """Rewrite docProps/app.xml so no generator fingerprint survives.

    python-docx has no high-level API for the extended-properties part
    and never parses it into an element tree, it treats the part as an
    opaque blob and writes it through unchanged. That means editing the
    blob directly, before save, is the only way to reach it, and it is
    guaranteed to be exactly what ends up in the saved package.
    """
    package = doc.part.package
    for part in package.iter_parts():
        if str(part.partname) != _APP_PROPERTIES_PARTNAME:
            continue
        xml = part.blob.decode("utf-8")
        xml = re.sub(
            r"<Application>.*?</Application>",
            "<Application>Microsoft Office Word</Application>",
            xml,
        )
        xml = re.sub(r"<Company>.*?</Company>", "<Company/>", xml)
        xml = re.sub(r"<Manager>.*?</Manager>", "<Manager/>", xml)
        # Final safety net: strip any remaining generator fingerprint,
        # whatever field it turns up in.
        xml = _TELL_PATTERN.sub("Microsoft Office Word", xml)
        part._blob = xml.encode("utf-8")  # noqa: SLF001 -- opaque blob part, no public setter
        return


def resolve_author_from_header_lines(lines):
    """Resolve an author name from a resume's block-0 header lines.

    Mirrors md_to_docx.py's render_header(): the name is the first
    non-blank line of block 0.

    Raises:
        ValueError: if no line in the header carries a non-blank name.
    """
    for line in lines:
        stripped = line.strip()
        if stripped:
            return stripped
    raise ValueError(
        "could not resolve an author name: resume header (block 0) has no non-blank line"
    )


def resolve_author_from_profile(profile_path=os.path.join("data", "profile.md")):
    """Resolve an author name from the "- **Name:** ..." field in
    data/profile.md. Used by writers whose own source document carries no
    name of its own (cheat sheets, cover letters).

    Args:
        profile_path: path to profile.md, resolved relative to the
            current working directory (writers are always invoked with
            the repo root as cwd). Overridable for tests.

    Raises:
        ValueError: if the file does not exist, or has no non-blank Name
            field. There is no silent fallback.
    """
    if not os.path.isfile(profile_path):
        raise ValueError(f"could not resolve an author name: {profile_path} not found")
    with open(profile_path, encoding="utf-8") as f:
        text = f.read()
    match = _NAME_FIELD_PATTERN.search(text)
    if not match or not match.group(1).strip():
        raise ValueError(
            f"could not resolve an author name: no '- **Name:** ...' field found in {profile_path}"
        )
    return match.group(1).strip()
